"""add payment fields to bookings

Revision ID: bc1fd4c309a1
Revises: bed75f0e6cae
Create Date: 2025-12-02 15:04:28.084771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1fd4c309a1'
down_revision: Union[str, Sequence[str], None] = 'bed75f0e6cae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('check_in', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('check_out', sa.Date(), nullable=False))
    op.add_column('bookings', sa.Column('total_price', sa.Float(), nullable=False))
    op.add_column('bookings', sa.Column('payment_proof', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True))
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_column('bookings', 'start_date')
    op.drop_column('bookings', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('bookings', sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'payment_proof')
    op.drop_column('bookings', 'total_price')
    op.drop_column('bookings', 'check_out')
    op.drop_column('bookings', 'check_in')
    # ### end Alembic commands ###
